services:
  labpcp-db:
    image: postgres:16-alpine
    container_name: labpcp-db
    environment:
      POSTGRES_DB: labpcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - labpcp-network

  labpcp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labpcp-backend
    volumes:
    - ./src:/app/src
    ports:
      - "8081:8081"
    depends_on:
      - labpcp-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://labpcp-db:5432/labpcp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - labpcp-network
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: labpcp-pgadmin
    restart: always
    depends_on:
      - labpcp-db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8000:80
    networks:
      - labpcp-network

volumes:
  postgres_data:

networks:
  labpcp-network:
    driver: bridge